// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/me": {
            "get": {
                "description": "Требует access token в заголовке Authorization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получить ID аутентифицированного пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003caccess_token\u003e",
                        "description": "Bearer access_token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Swagger-Test",
                        "description": "User-Agent",
                        "name": "User-Agent",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "127.0.0.1",
                        "description": "IP адрес клиента",
                        "name": "X-Forwarded-For",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/new_session/{user_id}": {
            "get": {
                "description": "Создает новую сессию для пользователя. Возвращает access token в заголовке и refresh token в cookie.",
                "tags": [
                    "auth"
                ],
                "summary": "Создать новую сессию",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0921ac27-5ec4-4031-a8f2-665e9c3c9eb3",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Swagger-Test",
                        "description": "User-Agent",
                        "name": "User-Agent",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "127.0.0.1",
                        "description": "IP адрес клиента",
                        "name": "X-Forwarded-For",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        },
                        "headers": {
                            "Access-Token": {
                                "type": "string",
                                "description": "Bearer \u003caccess_token\u003e"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "get": {
                "description": "Требует access token в заголовке Authorization и cookie refresh_token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновить access/refresh токены",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003caccess_token\u003e",
                        "description": "Bearer access_token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Swagger-Test",
                        "description": "User-Agent",
                        "name": "User-Agent",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "127.0.0.1",
                        "description": "IP адрес клиента",
                        "name": "X-Forwarded-For",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        },
                        "headers": {
                            "Access-Token": {
                                "type": "string",
                                "description": "Bearer \u003cnew_access_token\u003e"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/refresh/revoke": {
            "post": {
                "description": "Требует access token в заголовке Authorization и cookie refresh_token. Делает refresh токен невалидным и access token помещает в blacklist.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Отозвать сессию",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003caccess_token\u003e",
                        "description": "Bearer access_token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Swagger-Test",
                        "description": "User-Agent",
                        "name": "User-Agent",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "127.0.0.1",
                        "description": "IP адрес клиента",
                        "name": "X-Forwarded-For",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Auth Service",
	Description:      "API аутентификации и авторизации",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
